name: Run Tests with pytest

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch (you can change it to your default branch)

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can specify the version you need, e.g., 3.8, 3.9, etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Set PYTHONPATH using setup.sh
      run: |
        export PYTHONPATH=$(pwd)/src:$PYTHONPATH
    
    - name: Run tests
      run: |
        pytest tests/  # This runs all the tests under the 'tests/' folder
